config/routes.rb
Rails.application.routes.draw do

  get 'pages/health'
  root 'pages#static', page: 'home'

  get ':page', to: 'pages#static'

  get 'pages/perks'
  get 'pages/index'
  get 'pages/hub'
  get 'pages/financial'
  get 'pages/learning'
  get 'pages/credit'
  get 'pages/profile'
  get 'pages/recognition'
  get 'pages/redeemed'
  get 'pages/perkbox'
  get 'pages/debt'
  get 'pages/holiday'
  get 'pages/wfh'
  get 'pages/head'
  get 'pages/yoga'
  get 'pages/coffee'
  get 'pages/netflix'
  get 'pages/credits25'
  get 'pages/sanctus'
  get 'pages/medical'
  get 'pages/dental'
  get 'pages/beer'
  get 'pages/holiday2'
  get 'pages/credits50'
  get 'pages/credits100'
  get 'pages/hawaii'
  get 'pages/asos'
  get 'pages/peer'
  get 'pages/adidas'
  get 'pages/apple'
  get 'pages/netflix2'
  get 'pages/nike'
  get 'pages/virgin'
  get 'pages/apple'
  get 'pages/john'
  get 'pages/asos2'
  get 'pages/tesco'
  get 'pages/franco'
  get 'pages/bill'
  get 'pages/premium'
  get 'pages/spotify'
  get 'pages/home'
  get 'pages/financial2'
  get 'pages/financial3'
  get 'pages/marketplace'
  get 'pages/notifications'
  get 'pages/feedback'
  get 'pages/youtube'
  get 'pages/lynda'
  get 'pages/skillshare'
  get 'pages/amazon'
  get 'pages/audible'
  get 'pages/udemy'
  get 'pages/physio'
  get 'pages/health'
  get 'pages/critical'
  get 'pages/dentalcashplan'
  get 'pages/financialadvice'
  get 'pages/healthcashplan'
  get 'pages/mental'
  get 'pages/health'
  get 'pages/medinsurance'
  get 'pages/healthinsurance'
  get 'pages/eap'
  get 'pages/councelling'
  get 'pages/purchases'
  get 'pages/splash'
  get 'pages/signup1'
  get 'pages/signup2'
  get 'pages/signup3'
  get 'pages/signup4'
  get 'pages/signup5'
  get 'pages/perks2'
  get 'pages/company'
  get 'pages/homeperks'
  get 'pages/hubperks'
  get 'pages/perksperks'
  get 'pages/marketplaceperks'
  get 'pages/financialperks'
  get 'pages/learningperks'
  get 'pages/premiumperks'
  get 'pages/companyperks'
  get 'pages/profileperks'
  get 'pages/purchasesperks'
  get 'pages/notificationsperks'
  get 'pages/creditperks'
  get 'pages/nikeperks'
  get 'pages/virginperks'
  get 'pages/johnperks'
  get 'pages/homerew'
  get 'pages/hubrew'
  get 'pages/perksrew'
  get 'pages/marketplacerew'
  get 'pages/financialrew'
  get 'pages/learningrew'
  get 'pages/premiumrew'
  get 'pages/companyrew'
  get 'pages/profilerew'
  get 'pages/purchasesrew'
  get 'pages/notificationsrew'
  get 'pages/creditrew'
  get 'pages/nikerew'
  get 'pages/virginrew'
  get 'pages/johnrew'
  get 'pages/splashemployee'
  get 'pages/signup6'
  get 'pages/manageteam'
  get 'pages/insights'
  get 'pages/teamprofile'
  get 'pages/teamcredit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def perks
  end

  def hub
  end

  def financial
  end

  def learning
  end

  def credit
  end

  def profile
  end

  def recognition
  end

  def redeemed
  end

  def perkbox
  end

  def debt
  end

  def coffee
  end

  def netflix
  end

  def holiday
  end

  def wfh
  end

  def head
  end

  def yoga
  end

  def company
  end

  def perks2
  end

  def credits25
  end

  def index
  end

  def sanctus
  end

  def medical
  end

  def beer
  end

  def holiday2
  end

  def credits50
  end

  def credits100
  end

  def hawaii
  end

  def asos
  end

  def peer
  end

  def adidas
  end

  def netflix2
  end

  def nike
  end

  def virgin
  end

  def apple
  end

  def john
  end

  def asos2
  end

  def tesco
  end

  def franco
  end

  def bill
  end

  def premium
  end

  def spotify
  end

  def financial2
  end

  def marketplace
  end

  def notifications
  end

  def feedback
  end

  def youtube
  end

  def lynda
  end

  def skillshare
  end

  def amazon
  end

  def audible
  end

  def udemy
  end

  def physio
  end

  def health
  end

  def critical
  end

  def dentalcashplan
  end

  def financialadvice
  end

  def healthcashplan
  end

  def healthinsurance
  end

  def mental
  end

  def medinsurance
  end

  def purchases
  end

  def splash
  end

  def signup1
  end

  def signup2
  end

  def signup3
  end

  def signup4
  end

  def signup5
  end

  def homeperks
  end

  def hubperks
  end

  def manageteam
  end

  def perksperks
  end

  def marketplaceperks
  end

  def financialperks
  end

  def learningperks
  end

  def premiumperks
  end

  def companyperks
  end

  def profileperks
  end

  def purchasesperks
  end

  def notificationsperks
  end

  def creditperks
  end

  def nikeperks
  end

  def virginperks
  end

  def johnperks
  end

  def splashemployee
  end

  def homerew
  end

  def hubrew
  end

  def perksrew
  end

  def marketplacerew
  end

  def financialrew
  end

  def learningrew
  end

  def premiumrew
  end

  def companyrew
  end

  def profilerew
  end

  def purchasesrew
  end

  def notificationsrew
  end

  def creditrew
  end

  def nikerew
  end

  def virginrew
  end

  def johnrew
  end

  def signup6
  end

  def insights
  end

  def teamprofile
  end

  def teamcredit
  end



  def static
    render params[:page].underscore.to_s
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_breadcrumblearningperks.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/pages/marketplace">Browse Marketplace</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Learning & Development</li>
        </ol>
      </nav>
      <br>
    </div>
  </div>
</div>

app/views/layouts/_breadcrumboffers.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/pages/marketplace">The Marketplace</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Everyday Offers</li>
        </ol>
      </nav>
      <br>
    </div>
  </div>
</div>

app/views/layouts/_breadcrumboffersperks.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/pages/marketplaceperks">Browse Marketplace</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Everyday Offers</li>
        </ol>
      </nav>
      <br>
    </div>
  </div>
</div>

app/views/layouts/_navigation2.html.erb
<div class="navbar-container ">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary-3">
        <div class="container-fluid">
          <a class="navbar-brand fade-page" href="/pages/home">
            <img class="logo" src="/perkbox.png" alt="Leap">
          </a>
          <div class="d-flex align-items-center order-lg-3">
            

            <li class="nav-item">  
              <a href="#" class="nav-link nav-link-icon"><i class="fa fa-search" aria-hidden="true"></i></a>
            </li>
            <li class="nav-item">  
              <a href="/pages/credit" class="nav-link nav-link-icon credit"><i class="fa fa-diamond" aria-hidden="true"></i> 150 Credits</a>
            </li>
            <li class="nav-item">  
              <a href="#" class="nav-link nav-link-icon"><i class="fa fa-bell" aria-hidden="true"></i></a>
            </li>
            
        





            <div class="dropdown ml-2">
              <img src="/avatar.png" alt="User" class="avatar avatar-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="dropdown-menu dropdown-menu-right dropdown-content">
                <h6>Joe Blogs</h6>

                <% if current_page?(pages_profile_path) -%>
                  <a href="/pages/profile" class="dropdown-item active">My Profile</a>
                <% else %>
                  <a href="/pages/profile" class="dropdown-item">My Profle</a>
                <% end %>

                <% if current_page?(pages_recognition_path) -%>
                  <a href="#" class="dropdown-item active">My Rewards & Recognitions</a>
                <% else %>
                  <a href="#" class="dropdown-item">My Rewards & Recognitions</a>
                <% end %>



                <% if current_page?(pages_redeemed_path) -%>
                  <a href="#" class="dropdown-item active">Purchase & Redemption History</a>
                <% else %>
                  <a href="#" class="dropdown-item">Purchase & Redemption History</a>
                <% end %>

                <a class="dropdown-item" href="#">Help & Support</a>
                <a class="dropdown-item" href="#">Logout</a>
              </div>
            </div>
            <div class="ml-2">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M3 17C3 17.5523 3.44772 18 4 18H20C20.5523 18 21 17.5523 21 17V17C21 16.4477 20.5523 16 20 16H4C3.44772 16 3 16.4477 3 17V17ZM3 12C3 12.5523 3.44772 13 4 13H20C20.5523 13 21 12.5523 21 12V12C21 11.4477 20.5523 11 20 11H4C3.44772 11 3 11.4477 3 12V12ZM4 6C3.44772 6 3 6.44772 3 7V7C3 7.55228 3.44772 8 4 8H20C20.5523 8 21 7.55228 21 7V7C21 6.44772 20.5523 6 20 6H4Z" fill="#212529"></path>
                </svg>

              </button>
            </div>
          </div>
          <div class="collapse navbar-collapse justify-content-between order-lg-2">
            <div class="py-2 py-lg-0">
              <ul class="navbar-nav">

                <% if current_page?(pages_hub_path) -%>
                  
                  <li class="nav-item ml-1"><a href="/pages/hub" class="nav-link active">Company Hub</a>
                  </li>

                <% else %>

                  <li class="nav-item ml-1"><a href="/pages/hub" class="nav-link">Company Hub</a>
                  </li>

                <% end %>

                <% if current_page?(pages_perks_path) -%>
                  
                  <li class="nav-item ml-1"><a href="/pages/perks" class="nav-link active">Company Benefits</a>
                  </li>

                <% else %>

                  <li class="nav-item ml-1"><a href="/pages/perks" class="nav-link">Company Benefits</a>
                  </li>

                <% end %>

                <li class="nav-item dropdown">

                  <% if current_page?(pages_financial_path) or current_page?(pages_learning_path) or current_page?(pages_perkbox_path) or current_page?(pages_premium_path) -%>
                    <a href="/pages/perkbox" class="nav-link active dropdown-toggle" data-toggle="dropdown-grid" aria-expanded="false" aria-haspopup="true">Perkbox Marketplace</a>
                  <% else %>
                    <a href="/pages/perkbox" class="nav-link dropdown-toggle" data-toggle="dropdown-grid" aria-expanded="false" aria-haspopup="true">Perkbox Marketplace</a>
                  <% end %>

                  <div class="dropdown-menu row">
                    <div class="col-4" data-dropdown-content>
                      <div class="bg-white rounded border shadow-lg o-hidden">
                        <div class="list-group list-group-flush">
                          <a href="/pages/financial2" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Everyday Savings</h5></span>
                              <div class="text-small text-muted">Get free codes to save money on the things that matter most to you. Earn back credit when you spend locally.</div>
                            </div>
                          </a>
                          <a href="/pages/financial3" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Perkbox Store <i class="fa fa-diamond" aria-hidden="true"></i></h5></span>
                              <div class="text-small text-muted">Spend your credit on our carefully curated partners to help you get the best out of life, both in and out of work.</div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

               
                
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </div>

app/views/layouts/_navigationperks.html.erb
<div class="navbar-container ">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary-3">
        <div class="container-fluid">
          <a class="navbar-brand fade-page" href="/pages/homeperks">
            <img class="logo" src="/perkbox.png" alt="Leap">
          </a>
          <div class="d-flex align-items-center order-lg-3">
            

            <li class="nav-item">  
              <a href="#" class="nav-link nav-link-icon"><i class="fa fa-search" aria-hidden="true"></i></a>
            </li>
            <li class="nav-item">  
              <a href="/pages/creditperks" class="nav-link nav-link-icon credit"><i class="fa fa-diamond" aria-hidden="true"></i> 150 Credits</a>
            </li>
            <li class="nav-item">  
              <a href="/pages/notificationsperks" class="nav-link nav-link-icon"><i class="fa fa-bell" aria-hidden="true"></i></a>
            </li>
            
        





            <div class="dropdown ml-2">
              <img src="/avatar.png" alt="User" class="avatar avatar-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="dropdown-menu dropdown-menu-right dropdown-content">
                <h6>Joe Bloggs</h6>

                <% if current_page?(pages_profile_path) -%>
                  <a href="/pages/profileperks" class="dropdown-item active">My Profile</a>
                <% else %>
                  <a href="/pages/profileperks" class="dropdown-item">My Profile</a>
                <% end %>

                <% if current_page?(pages_purchases_path) -%>
                  <a href="/pages/purchasesperks" class="dropdown-item active">My Redeemed Codes</a>
                <% else %>
                  <a href="/pages/purchasesperks" class="dropdown-item">My Redeemed Codes</a>
                <% end %>    

                <% if current_page?(pages_notifications_path) -%>
                  <a href="/pages/notificationsperks" class="dropdown-item active">My Activity</a>
                <% else %>
                  <a href="/pages/notificationsperks" class="dropdown-item">My Activity</a>
                <% end %>            

                <a class="dropdown-item" href="#">Help & Support</a>
                <a class="dropdown-item" href="/pages/splash">Logout</a>
              </div>
            </div>
            <div class="ml-2">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M3 17C3 17.5523 3.44772 18 4 18H20C20.5523 18 21 17.5523 21 17V17C21 16.4477 20.5523 16 20 16H4C3.44772 16 3 16.4477 3 17V17ZM3 12C3 12.5523 3.44772 13 4 13H20C20.5523 13 21 12.5523 21 12V12C21 11.4477 20.5523 11 20 11H4C3.44772 11 3 11.4477 3 12V12ZM4 6C3.44772 6 3 6.44772 3 7V7C3 7.55228 3.44772 8 4 8H20C20.5523 8 21 7.55228 21 7V7C21 6.44772 20.5523 6 20 6H4Z" fill="#212529"></path>
                </svg>

              </button>
            </div>
          </div>
          <div class="collapse navbar-collapse justify-content-between order-lg-2">
            <div class="py-2 py-lg-0">
              <ul class="navbar-nav">

                <% if current_page?(pages_hubperks_path) -%>
                  
                  <li class="nav-item ml-1"><a href="/pages/hubperks" class="nav-link active">Company Hub</a>
                  </li>

                <% else %>

                  <li class="nav-item ml-1"><a href="/pages/hubperks" class="nav-link">Company Hub</a>
                  </li>

                <% end %>

                <% if current_page?(pages_perks_path) or current_page?(pages_perks2_path) or current_page?(pages_holiday2_path) or current_page?(pages_medical_path) or current_page?(pages_dental_path) or current_page?(pages_beer_path) or current_page?(pages_asos_path) or current_page?(pages_yoga_path) or current_page?(pages_peer_path) or current_page?(pages_head_path) or current_page?(pages_netflix_path) or current_page?(pages_sanctus_path) or current_page?(pages_mental_path) -%>
                  
                  <li class="nav-item ml-1"><a href="/pages/perksperks" class="nav-link active">My Perks</a>
                  </li>

                <% else %>

                  <li class="nav-item ml-1"><a href="/pages/perksperks" class="nav-link">My Perks</a>
                  </li>

                <% end %>

                <li class="nav-item dropdown">

                  <% if current_page?(pages_financial_path) or current_page?(pages_learning_path) or current_page?(pages_perkbox_path) or current_page?(pages_premium_path) or current_page?(pages_nike_path) or current_page?(pages_virgin_path) or current_page?(pages_john_path) or current_page?(pages_youtube_path) or current_page?(pages_spotify_path) or current_page?(pages_asos2_path) or current_page?(pages_netflix2_path) or current_page?(pages_tesco_path) or current_page?(pages_franco_path) or current_page?(pages_bill_path) or current_page?(pages_apple_path) or current_page?(pages_adidas_path) -%>
                    <a href="/pages/perkbox" class="nav-link active dropdown-toggle" data-toggle="dropdown-grid" aria-expanded="false" aria-haspopup="true">Browse Marketplace <i class="fa fa-diamond" aria-hidden="true"></i></a>
                  <% else %>
                    <a href="/pages/perkbox" class="nav-link dropdown-toggle" data-toggle="dropdown-grid" aria-expanded="false" aria-haspopup="true">Browse Marketplace <i class="fa fa-diamond" aria-hidden="true"></i></a>
                  <% end %>

                  <div class="dropdown-menu row">
                    <div class="col-5 px-0" data-dropdown-content>
                      <div class="bg-white rounded border shadow-lg o-hidden">
                        <div class="list-group list-group-flush">
                          <a href="/pages/financialperks" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Everyday Offers</h5></span>
                              <div class="text-small text-muted">Explore hundreds of everyday offers and get access to the things that matter most to you.</div>
                            </div>
                          </a>
                          <a href="/pages/learningperks" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Learning & Development</h5></span>
                              <div class="text-small text-muted">Access our carefully curated partners to help you learn, grow and develop both in and out of work.</div>
                            </div>
                          </a>
                          <a href="/pages/premiumperks" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Health & Support</h5></span>
                              <div class="text-small text-muted">Look after your health and get support when you need it most.</div>
                            </div>
                          </a>
                           <a href="/pages/companyperks" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Company Name Catalogue</h5></span>
                              <div class="text-small text-muted">We've created some bespoke company perks that you're able to purchase with your credit.</div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

               
                
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </div>

app/views/layouts/_navigationperksmedrec.html.erb
<div class="navbar-container ">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary-3">
        <div class="container-fluid">
          <a class="navbar-brand fade-page" href="/pages/home">
            <img class="logo" src="/perkbox.png" alt="Leap">
          </a>
          <div class="d-flex align-items-center order-lg-3">
            

            <li class="nav-item">  
              <a href="#" class="nav-link nav-link-icon"><i class="fa fa-search" aria-hidden="true"></i></a>
            </li>
            <li class="nav-item">  
              <a href="/pages/credit" class="nav-link nav-link-icon credit"><i class="fa fa-diamond" aria-hidden="true"></i> 150 Credits</a>
            </li>
            <li class="nav-item">  
              <a href="/pages/notifications" class="nav-link nav-link-icon"><i class="fa fa-bell" aria-hidden="true"></i></a>
            </li>
            
        





            <div class="dropdown ml-2">
              <img src="/avatar.png" alt="User" class="avatar avatar-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="dropdown-menu dropdown-menu-right dropdown-content">
                <h6>Joe Bloggs</h6>

                <% if current_page?(pages_profile_path) -%>
                  <a href="/pages/profile" class="dropdown-item active">My Profile</a>
                <% else %>
                  <a href="/pages/profile" class="dropdown-item">My Profile</a>
                <% end %>
                  
                <% if current_page?(pages_recognition_path) -%>
                  <a href="/pages/recognition" class="dropdown-item active">My Reward & Recognition</a>
                <% else %>
                  <a href="/pages/recognition" class="dropdown-item">My Reward & Recognition</a>
                <% end %>

                <% if current_page?(pages_purchases_path) -%>
                  <a href="/pages/purchases" class="dropdown-item active">My Redeemed Codes</a>
                <% else %>
                  <a href="/pages/purchases" class="dropdown-item">My Redeemed Codes</a>
                <% end %>    

                <% if current_page?(pages_notifications_path) -%>
                  <a href="/pages/notifications" class="dropdown-item active">My Activity</a>
                <% else %>
                  <a href="/pages/notifications" class="dropdown-item">My Activity</a>
                <% end %>            

                <a class="dropdown-item" href="#">Help & Support</a>
                <a class="dropdown-item" href="/pages/splash">Logout</a>
              </div>
            </div>
            <div class="ml-2">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M3 17C3 17.5523 3.44772 18 4 18H20C20.5523 18 21 17.5523 21 17V17C21 16.4477 20.5523 16 20 16H4C3.44772 16 3 16.4477 3 17V17ZM3 12C3 12.5523 3.44772 13 4 13H20C20.5523 13 21 12.5523 21 12V12C21 11.4477 20.5523 11 20 11H4C3.44772 11 3 11.4477 3 12V12ZM4 6C3.44772 6 3 6.44772 3 7V7C3 7.55228 3.44772 8 4 8H20C20.5523 8 21 7.55228 21 7V7C21 6.44772 20.5523 6 20 6H4Z" fill="#212529"></path>
                </svg>

              </button>
            </div>
          </div>
          <div class="collapse navbar-collapse justify-content-between order-lg-2">
            <div class="py-2 py-lg-0">
              <ul class="navbar-nav">

                <% if current_page?(pages_hub_path) -%>
                  
                  <li class="nav-item ml-1"><a href="/pages/hub" class="nav-link active">Company Hub</a>
                  </li>

                <% else %>

                  <li class="nav-item ml-1"><a href="/pages/hub" class="nav-link">Company Hub</a>
                  </li>

                <% end %>

                <% if current_page?(pages_perks_path) or current_page?(pages_perks2_path) or current_page?(pages_holiday2_path) or current_page?(pages_medical_path) or current_page?(pages_dental_path) or current_page?(pages_beer_path) or current_page?(pages_asos_path) or current_page?(pages_yoga_path) or current_page?(pages_peer_path) or current_page?(pages_head_path) or current_page?(pages_netflix_path) or current_page?(pages_sanctus_path) or current_page?(pages_mental_path) -%>
                  
                  <li class="nav-item ml-1"><a href="/pages/perks2" class="nav-link active">My Perks</a>
                  </li>

                <% else %>

                  <li class="nav-item ml-1"><a href="/pages/perks2" class="nav-link">My Perks</a>
                  </li>

                <% end %>

                <li class="nav-item dropdown">

                  <% if current_page?(pages_financial_path) or current_page?(pages_learning_path) or current_page?(pages_perkbox_path) or current_page?(pages_premium_path) or current_page?(pages_nike_path) or current_page?(pages_virgin_path) or current_page?(pages_john_path) or current_page?(pages_youtube_path) or current_page?(pages_spotify_path) or current_page?(pages_asos2_path) or current_page?(pages_netflix2_path) or current_page?(pages_tesco_path) or current_page?(pages_franco_path) or current_page?(pages_bill_path) or current_page?(pages_apple_path) or current_page?(pages_adidas_path) -%>
                    <a href="/pages/perkbox" class="nav-link active dropdown-toggle" data-toggle="dropdown-grid" aria-expanded="false" aria-haspopup="true">Browse Marketplace <i class="fa fa-diamond" aria-hidden="true"></i></a>
                  <% else %>
                    <a href="/pages/perkbox" class="nav-link dropdown-toggle" data-toggle="dropdown-grid" aria-expanded="false" aria-haspopup="true">Browse Marketplace <i class="fa fa-diamond" aria-hidden="true"></i></a>
                  <% end %>

                  <div class="dropdown-menu row">
                    <div class="col-5 px-0" data-dropdown-content>
                      <div class="bg-white rounded border shadow-lg o-hidden">
                        <div class="list-group list-group-flush">
                          <a href="/pages/financial" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Everyday Offers</h5></span>
                              <div class="text-small text-muted">Explore hundreds of everyday offers and get access to the things that matter most to you.</div>
                            </div>
                          </a>
                          <a href="/pages/learning" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Learning & Development</h5></span>
                              <div class="text-small text-muted">Access our carefully curated partners to help you learn, grow and develop both in and out of work.</div>
                            </div>
                          </a>
                          <a href="/pages/premium" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Health & Support</h5></span>
                              <div class="text-small text-muted">Look after your health and get support when you need it most.</div>
                            </div>
                          </a>
                           <a href="/pages/company" class="list-group-item list-group-item-action d-flex align-items-center p-3">
                            <div class="text-body ml-3">
                              <span><h5>Company Name Catalogue</h5></span>
                              <div class="text-small text-muted">We've created some bespoke company perks that you're able to purchase with your credit.</div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

               
                
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </div>